* [[https://jordanbpeterson.com/2017/03/great-books/][A Categorized Book List]]
** Clinical Psychology and Personality

   1    Sigmund Freud: The Interpretation of Dreams
   2    Carl Jung: Modern Man in Search of a Soul
   3    Carl Jung: Answer to Job
   4    Carl Jung: Archetypes of the Collective Unconscious
   5    Carl Jung: Aion
   6    Carl Jung: Psychology: East and West
   7    Carl Rogers: A Way of Being
   8    Carl Rogers: On Becoming a Person
   9    Jean Piaget: Play, Dreams and Imitation in Childhood
   10    Jean Piaget: The Moral Judgment of the Child
   11    Henri Ellenberger: The Discovery of the Unconscious
   12    Erich Neumann: The Origins and History of Consciousness
   13    Erich Neumann: The Great Mother
   14    Ernest Becker: The Denial of Death
   15    May, R., Angel, E., & Ellenberger, H: Existence: A new dimension in psychiatry and psychology

** General

   1     Derek J. de Solla Price: Little Science, Big Science
   2     Hans Eysenck: Genius
   3     Hernando De Soto: The Mystery of Capital: Why Capitalism Triumphs in the West and Fails Everywhere Else
   4     John Gall: Systemantics: How Systems Work and Especially How They Fail
   5     Theodore Dalrymple: Life at the Bottom: The Worldview That Makes the Underclass

** Religion and Religious History

   1    Huston Smith (introductory): The World’s Religions
   2    A History of Religious Ideas (Vol. 1, Vol. 2, Vol. 3) – Mircea Eliade
   3    Jeffrey Burton Russell: Mephistopheles: The Devil in the Modern World
   4    The Bible: Designed to be Read as Living Literature
   5     Bernard Lewis: The Crisis of Islam

** My Books

   1     Jordan B. Peterson: Maps of Meaning

** Neuroscience

   1    Jeffrey Gray and Neil McNaughton: The Neuropsychology of Anxiety
   2    Jaak Panksepp: Affective Neuroscience
   3    Joseph LeDoux: The Emotional Brain
   4    Larry Swanson: Brain Architecture: Understanding the Basic Plan
   5    JJ Gibson: An Ecological Approach to Visual Perception
   6    Elkhonon Goldberg: The New Executive Brain

** Literature/Philosophy

   1    Fyodor Dostoevsky: The Devils
   2    Fyodor Dostoevsky: The Idiot
   3    Nikos Kazantzakis: The Fratricides
   4    Nikos Kazantzakis: Zorba the Greek
   5    Mikhail Bulgakov: The Master and Margarita
   6    Solzhenitsyn: The First Circle
   7    Solzhenitsyn: Cancer Ward
   8    Friedrich Nietzsche: The Antichrist
   9    Friedrich Nietzsche: The Gay Science
   10    Northrop Frye: The Great Code
   11    Northrop Frye: Words with Power
   12    Robert Pirsig: Zen and the Art of Motorcycle Maintenance
   
** Biography

   1 Henri Troyat: Tolstoy

** History

   1    Edvard Radzinsky: Stalin: The First In-depth Biography Based on Explosive New Documents from Russia’s Secret Archives
   2    Theodore M. Porter: The Rise of Statistical Thinking 1820-1900
   3    William L. Shirer: The Rise and Fall of the Third Reich
* [[https://jordanbpeterson.com/2016/11/book-list/][Book list]]
  
  1. Brave New World – Aldous Huxley
  2. 1984 – George Orwell
  3. Road To Wigan Pier – George Orwell
  4. Crime And Punishment – Fyodor Dostoevsky
  5. Demons – Fyodor Dostoevsky
  6. Beyond Good And Evil – Friedrich Nietzsche
  7. Ordinary Men – Christopher Browning
  8. The Painted Bird – Jerzy Kosinski
  9. The Rape of Nanking – Iris Chang
  10. Gulag Archipelago (Vol. 1, Vol. 2, & Vol. 3) – Aleksandr Solzhenitsyn
  11. Man’s Search for Meaning – Viktor Frankl
  12. Modern Man in Search of A Soul – Carl Jung
  13. Maps Of Meaning: The Architecture of Belief – Jordan B. Peterson
  14. A History of Religious Ideas (Vol. 1, Vol. 2, Vol. 3) – Mircea Eliade
  15. Affective Neuroscience – Jaak Panksepp
